swagger: "2.0"
info:
  title: "Prefix Search API"
  description: "API for searching IP prefixes"
  version: "1.0.0"
paths:
  /api/v1/prefixes:
    get:
      summary: "Search for IP prefixes"
      parameters:
        - name: ip
          in: query
          type: string
          required: true
          description: "The IP address to search."
      responses:
        200:
          description: "A list of matching results."
    post:
      summary: "Search for IP prefixes in a batch"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              ips:
                type: array
                items:
                  type: string
          description: "The list of IP addresses to search."
      responses:
        200:
          description: "A list of matching results."
